DROP TABLE IF EXISTS account CASCADE;
DROP TABLE IF EXISTS tweet CASCADE;
DROP TABLE IF EXISTS follows CASCADE;
DROP TABLE IF EXISTS hashtag_used CASCADE;
DROP TABLE IF EXISTS mentions CASCADE;
DROP TABLE IF EXISTS reply_to CASCADE;
DROP TABLE IF EXISTS retweet CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
